### Copyright 2022 Omar Suleiman

steps:

### Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/devops-343007/omar-react-image:${SHORT_SHA}', '.' ]

## Push / Publish
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devops-343007/omar-react-image:${SHORT_SHA}']
    images: ['gcr.io/devops-343007/omar-react-image:${SHORT_SHA}']

### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          PROJECT=devops-343007
        
          gcloud container clusters get-credentials "omar-cluster" \
            --project "devops-343007" \
            --zone "us-west2-a" 
          
          sed -i 's|gcr.io/devops-343007/omar-react-image:.*|gcr.io/devops-343007/omar-react-image:${SHORT_SHA}|' manifest.yml
          
          kubectl apply -f manifest.yml

### Timeout
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
