# Copyright 2018 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:

### Publish
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker push gcr.io/devops-analiza/omar-react-image:v1



### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
       
          PROJECT=devops-analiza
        
          
          gcloud container clusters get-credentials "omar-cluster" \
            --project "devops-analiza" \
            --zone "us-west1-a"  

          sed -i 's|gcr.io/devops-analiza/omar-react-image:.*|gcr.io/devops-analiza/omar-react-image:v1|' ./k8s/deployments/dev/*.yaml
          
          kubectl get ns v1 || kubectl create ns v1
          kubectl apply --namespace v1 --recursive -f k8s/deployments/dev
          kubectl apply --namespace v1 --recursive -f k8s/services

options:
 logging: CLOUD_LOGGING_ONLY