---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "prod"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-app"
  namespace: "prod"
  labels:
    app: "my-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-app"
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      containers:
      - name: "omar-react-image-sha256-1"
        image: "gcr.io/devops-analiza/omar-react-image-test:v1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "my-app-hpa-fyty"
  namespace: "prod"
  labels:
    app: "my-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "my-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
