apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: omar-app
spec:
    replicas: 1
    selector:
    matchLabels:
        app: omar-app
    template:
    metadata:
        labels:
        app: omar-app
    spec:
        containers:
        - name: omar-app

        image: gcr.io/devops-analiza/omar-react-image:v1

        ports:
        - containerPort: 80
        env:
            - name: PORT
            value: "80